# Generated by Django 5.1.3 on 2024-11-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('principal', models.CharField(max_length=20)),
                ('established_date', models.DateField()),
            ],
        ),
    ]
