# Generated by Django 5.1.3 on 2024-11-13 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangomanager', '0003_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
    ]
